apiVersion: v1
data:
  mapRoles: |
   - groups:  
    - system:bootstrappers
    - system:nodes
    rolearn: arn:aws:iam::081175417533:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DG9EFH8XW1TS
    username: system:node:{{EC2PrivateDNSName}}
   - groups:
    - system:masters
    rolearn: arn:aws:iam::081175417533:role/UdacityFlaskDeployCBKubectlRole
    username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-11T18:13:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4619"
  uid: a84ad633-25c1-4d56-8bf8-258f15c5dc53
