apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::081175417533:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-123WETMB0YHV4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::081175417533:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-12-12T14:13:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1858"
  uid: d566c8c0-a539-4a78-af50-8871d9c6d262
